<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sajjad Carpet</title>
    <style>
        body {
            margin: 0;
            background-color: rgb(221, 226, 230);
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            line-height: 1.5;
        }

        .header {
            background-color: rgb(180, 178, 18);
            list-style: none;
            padding: 20px 0;
            text-align: center;
            box-shadow: 0 2px 7px;
        }

        .header h1 {
            margin: 0;
            text-align: center;
            font-size: 2.5em;
            padding-bottom: 10px;
            /* background-color: antiquewhite; */


        }

        .header nav ul {
            list-style: none;
            text-decoration: none;
            justify-content: center;
            display: flex;
            gap: 30px;


        }

        .header nav a {
            text-decoration: none;
            font-weight: bold;
            transition: background-color 0.5s ease;
            border-radius: 5px;
            color: black;
        }

        .header nav a:hover {
            transition: background-color 1.5s ease;
            background-color: rgb(52, 201, 84);
        }

        .Gallery {
            padding: 40px 20px;
            max-width: 1200px;
            margin: 20px auto;
            background-color: aliceblue;
            box-shadow: 0 0 10px rgb(27, 24, 24);
        }

        .Gallery h2 {
            text-align: center;
            font-family: 2.2em;
            margin-bottom: 30px;
            color: rgb(82, 51, 5);
        }

        .Gallery-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 25px;
        }

        .Gallery-item {
            border: 1px solid rgb(19, 15, 15);
            border-radius: 5px;
            overflow: hidden;
            box-shadow: 0 2px 4px;
            transition: transform 0.5s ease-in-out, box-shadow 1s ease-in-out;
            background-color: aliceblue;
            display: flex;
        }

        .Gallery-item:hover {
            transform: translateY(-20px);
        }

        .Gallery-item img {
            width: 100%;
            height: 300px;
        }

        .footer {
            background-color: #333;
            color: white;
            padding: 40px 20px;
            text-align: center;
            margin-top: 40px;
        }

        .footer-content {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            gap: 30px;
            max-width: 1200px;
            margin: 0 auto;
            padding-bottom: 30px;
            border-bottom: 1px solid #333;
        }

        .footer-section {
            flex: 1;
            min-width: 250px;
            margin-bottom: 20px;
            text-align: left;
        }

        .footer-section h3 {
            color: #3498db;
            margin-bottom: 15px;
            font-size: 1.3em;
        }

        .footer-section p,
        .footer-section ul {
            font-size: 0.96em;
            color: #ccc;
        }

        .footer-section ul {
            list-style: none;
            padding: 15px;
        }

        .footer-section ul li {
            margin-bottom: 8px;
        }

        .footer-content ul li a {
            color: #ccc;
            text-decoration: none;
            transition: color 0.5s ease;
        }

        .footer-section ul li a:hover {
            color: #fff;
            text-decoration: underline;
            background-color: #795c5c;
        }
    </style>
</head>

<body>
    <header class="header">
        <h1>Al Areeq Capret and Furnishing</h1>
        <nav>
            <ul>
                <li><a href="#Home">Home</a></li>
                <li> <a href="#Gallery">Gallery</a></li>
                <li><a href="#Services">Services</a></li>
                <li><a href="#About Us">About Us</a></li>
            </ul>
        </nav>
    </header>

    <main class="Gallery">
        <h2>Ours Products and Creation see here</h2>
        <div class="Gallery-grid">
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
            <div class="Gallery-item">
                <img src="\media\Photos-001\IMG-20240423-WA0060.jpg" alt="">
            </div>
        </div>
    </main>

    <footer class="footer">
        <div class="footer-content">
            <div class="footer-section about-us " id="about">
                <h3>About us</h3>
                <p>Shahid Ali Carpet & Furnishing offers a wide range of high-quality carpets, sofas, and other
                    furnishing items. With years of experience, we pride ourselves on craftsmanship and customer
                    satisfaction. Located in Abu Dhabi - United Arab Emirates.</p>
            </div>
            <div class="footer-section contact-infor">
                <h1>Contact</h1>
                <p>E-Mail: @gmail.com</p>
                <p>Phone: </p>
                <p>Address: </p>
            </div>
            <div class=" footer-section quick-links">
                <h3>Quick links</h3>
                <ul>
                    <li> <a href="#Home">Home</a></li>
                    <li> <a href="#Gallery">Gallery</a></li>
                    <li> <a href="Services">Services</a></li>
                    <li> <a href="#Location">Location map</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom">
            &copy; 2025 Shahid Ali Carpet & Furnishing. All rights reserved.
        </div>
    </footer>


</body>

</html>
